# Generated by Django 5.0.2 on 2024-03-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctions_description_alter_auctions_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.CharField(max_length=3000),
        ),
    ]
