# Generated by Django 5.0.2 on 2024-03-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctions_description_alter_auctions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.CharField(max_length=20000),
        ),
    ]
