# Generated by Django 5.0.2 on 2024-03-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctions_description_alter_auctions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='day',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='month',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='year',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctions',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
