# Generated by Django 5.0.2 on 2024-03-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comments_day_comments_month_comments_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='biggest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
