# Generated by Django 5.0.2 on 2024-03-07 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctions_biggest_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wachlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wathlist', to='auctions.auctions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wathlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
