# Generated by Django 5.0.2 on 2024-03-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_wachlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wachlist',
            new_name='Watchlist',
        ),
    ]
